# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SnykIacRules < Formula
  desc "Write, debug, test, and bundle custom rules for Snyk Infrastructure as Code."
  homepage "https://snyk.io/"
  version "0.2.1"
  license "Apache-2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/snyk/snyk-iac-rules/releases/download/v0.2.1/snyk-iac-rules_0.2.1_Darwin_x86_64.tar.gz"
      sha256 "26faf209a61ae3cb1283288e1732b97a497968847c8355a637c41c200edbb483"
    end
    if Hardware::CPU.arm?
      url "https://github.com/snyk/snyk-iac-rules/releases/download/v0.2.1/snyk-iac-rules_0.2.1_Darwin_arm64.tar.gz"
      sha256 "9fe4fe84a5bb5638fa67bacba328aed1b18d16d65d0336821793134713e8a86a"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/snyk/snyk-iac-rules/releases/download/v0.2.1/snyk-iac-rules_0.2.1_Linux_x86_64.tar.gz"
      sha256 "4deee74770a1cda724f78fb286b5923401ecb3d6cc30140a3b5200f4f347b5a8"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/snyk/snyk-iac-rules/releases/download/v0.2.1/snyk-iac-rules_0.2.1_Linux_arm64.tar.gz"
      sha256 "c0e7f273d3e1a94c33371243b32052db7100dd4b2753be1d7195c3326ece7101"
    end
  end

  def install
    bin.install "snyk-iac-rules"
  end
end
