# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SnykIacRules < Formula
  desc "Write, debug, test, and bundle custom rules for Snyk Infrastructure as Code."
  homepage "https://snyk.io/"
  version "0.2.1"
  license "Apache-2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/snyk/snyk-iac-rules/releases/download/v0.2.1/snyk-iac-rules_0.2.1_Darwin_x86_64.tar.gz"
      sha256 "6474ec59ba94bc1f17be7e483252655f38a06c0b20adf063f0a6a8687ef06e18"
    end
    if Hardware::CPU.arm?
      url "https://github.com/snyk/snyk-iac-rules/releases/download/v0.2.1/snyk-iac-rules_0.2.1_Darwin_arm64.tar.gz"
      sha256 "19657e0a9d303c05e75512d3da9be967ef0d01d772ed6298fa3723e169c4b2de"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/snyk/snyk-iac-rules/releases/download/v0.2.1/snyk-iac-rules_0.2.1_Linux_x86_64.tar.gz"
      sha256 "d32ca90bec84b67f763691abc774560c228f6bd33dd626c3115322ea7516fa4f"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/snyk/snyk-iac-rules/releases/download/v0.2.1/snyk-iac-rules_0.2.1_Linux_arm64.tar.gz"
      sha256 "eca5d114d03b7b1f294df08611418d43321c8cdd0ece6461f7d7c4359259c399"
    end
  end

  def install
    bin.install "snyk-iac-rules"
  end
end
