# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SnykIacRules < Formula
  desc "Write, debug, test, and bundle custom rules for Snyk Infrastructure as Code."
  homepage "https://snyk.io/"
  version "1.5.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/snyk/snyk-iac-rules/releases/download/v1.5.3/snyk-iac-rules_1.5.3_Darwin_arm64.tar.gz"
      sha256 "ff43e1fe5e94cbe2ec23d86632ac0490ef884746e1cd2e3b8dacc0c56ddc538a"

      def install
        bin.install "snyk-iac-rules"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/snyk/snyk-iac-rules/releases/download/v1.5.3/snyk-iac-rules_1.5.3_Darwin_x86_64.tar.gz"
      sha256 "e4976ea321d6da1af3df2fbd4775564a58970101261a98c6ed10b2ec3dd79e63"

      def install
        bin.install "snyk-iac-rules"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/snyk/snyk-iac-rules/releases/download/v1.5.3/snyk-iac-rules_1.5.3_Linux_arm64.tar.gz"
      sha256 "a1127940db54ac913643d50502c2db33858dcea75bf7773d4774ce25b08e3fdf"

      def install
        bin.install "snyk-iac-rules"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/snyk/snyk-iac-rules/releases/download/v1.5.3/snyk-iac-rules_1.5.3_Linux_x86_64.tar.gz"
      sha256 "8787ffd94e39c929052c389d4b186e5e4e2bdd0ff1e08e66ae9b1f065f152ba5"

      def install
        bin.install "snyk-iac-rules"
      end
    end
  end
end
